# Generated by Django 4.2.3 on 2023-07-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='videos', to='myapp.category'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='videos', to='myapp.videometadata'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/'),
        ),
    ]
