# Generated by Django 4.2.3 on 2023-07-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_video_categories_alter_video_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='categories',
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='videos', to='myapp.videometadata'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
